# This GitHub action runs your tests for each commit push and/or PR.
name: Build
on:
  pull_request_target:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'examples/**'

jobs:
  tests:
    name: Terraform acceptance tests
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Setup Go 1.19
        uses: actions/setup-go@v4.1.0
        with:
          go-version: '1.19'
        id: go
      - name: Check out the code into the Go module directory
        uses: actions/checkout@v4.1.1
      - name: Get dependencies
        run: |
          go mod download
      - name: Run tests
        timeout-minutes: 10
        env:
          TF_ACC: "1"
          BLOXONE_HOST: ${{ secrets.BLOXONE_HOST }}
          BLOXONE_API_KEY: ${{ secrets.BLOXONE_API_KEY }}
          DHCP_HOST: ${{ secrets.DHCP_HOST }}
          DNS_HOST: ${{ secrets.DNS_HOST }}
        run: |
          go test -v -cover ./internal/...
