# This GitHub action runs your tests for each commit push and/or PR.
name: Build
on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'examples/**'

jobs:
  # ensure the code builds...
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-go@v4.1.0
        with:
          go-version: '1.19'
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test

  lint:
    name: Go Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-go@v4.1.0
        with:
          go-version: '1.19'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          args: --timeout=10m --max-issues-per-linter 0 --max-same-issues 0

  acc-test:
    name: Terraform acceptance tests
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 2
      - uses: actions/setup-go@v4.1.0
        with:
          go-version: '1.19'
      - name: Run tests
        timeout-minutes: 10
        env:
          TF_ACC: "1"
          BLOXONE_HOST: ${{ secrets.BLOXONE_HOST }}
          BLOXONE_API_KEY: ${{ secrets.BLOXONE_API_KEY }}
          DHCP_HOST: ${{ secrets.DHCP_HOST }}
          DNS_HOST: ${{ secrets.DNS_HOST }}
        run: |
          go test $(go list ./... | grep -v 'vendor') -v -cover
